"""Initial migration new 

Revision ID: 0c8b37bf12cc
Revises: 0691c079dc77
Create Date: 2024-12-10 22:00:01.638966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8b37bf12cc'
down_revision = '0691c079dc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=2048), nullable=False),
    sa.Column('keywords', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
